name: findana
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  # Dianjurkan menggunakan versi SDK terbaru yang kompatibel
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  # Ikon
  cupertino_icons: ^1.0.8

  # Formatting Tanggal dan Mata Uang (Sudah Anda masukkan)
  intl: ^0.20.2

  # Font (Sudah Anda masukkan)
  google_fonts: ^6.3.3

  # --- Dependensi Tambahan untuk Aplikasi Keuangan ---

  # Database Lokal
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1 # Diperlukan oleh sqflite

  # Manajemen State
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true